fs-webdev/create-react-app

packages/react-scripts/config/webpack.config.js, packages/react-scripts/config/webpackDevServer.config.js, packages/react-scripts/package-lock.json, packages/react-scripts/package.json
Conditionally change based on if `hf` exists in root node_modules.
* Copy webpack plugin - Used to copy over built (webpacked) hf code to `/static/hf` directory.
* `splitChunks` was causing issues for any files hf was loading via webpack.
* `index.html => _index.html` is so that we can serve it via express/ejs/snow
* `writeToDisk` is so snow can serve the files based on the manifestMap provided by hf's webpack build.
I created a prerelease of these changes and pushed it to prod via EF here: https://beta.familysearch.org/frontier/tyler-mvp/. The fact that it shows the green border around the page in helper mode means that it's working.
=> Support for HF

packages/react-scripts/scripts/utils/frontierInit.js, packages/react-scripts/template-ef/.buildpacks, packages/react-scripts/template-ef/heroku-prebuild.sh, packages/react-scripts/template-hf/Procfile, packages/react-scripts/template-hf/public/index.html, packages/react-scripts/template-hf/server.js, packages/react-scripts/template-hf/snow.config.js, packages/react-scripts/template-hf/src/setupProxy.js, packages/react-scripts/template-hf/views/index.ejs, packages/react-scripts/template/gitignore
* set default options for init (ef/hf)
* Add template files for hf
* Add `.env` and `/dist` to `.gitignore`
* Add s3 uploader to `.buildpack` in template-ef
=> Add template files for hf.

packages/react-scripts/scripts/utils/frontierInit.js, packages/react-scripts/template-ef/Procfile, packages/react-scripts/template-ef/server.js
* force ef for hf
* move server.js to root for ef
=> Force ef in hf.

packages/react-scripts/scripts/utils/frontierInit.js, packages/react-scripts/template-hf/src/setupProxy.js, packages/react-scripts/template/src/index.js
Added reach router to dependency list, configured client side routing in the setupProxies file and added root router to the index.js
=> add reachrouter, configure client side routing, add router to app

packages/react-scripts/scripts/utils/frontierInit.js, packages/react-scripts/template-ef/blueprint.yml, packages/react-scripts/template/i18next-scanner.config.js, packages/react-scripts/template/src/components/App.js, packages/react-scripts/template/src/components/home/Home.js, packages/react-scripts/template/src/components/home/Logo.js, packages/react-scripts/template/src/components/user/UserInfo.js, packages/react-scripts/template/src/index.js
Depends on updates to `@fs/locale`
=> Add i18n to CRA starter template

packages/react-scripts/scripts/utils/frontierInit.js
We need the auth in Heroku or the builds will fail. If this was supposed to be removed, then we need a buildpack or other solution.
=> Restore Heroku prebuild

package-lock.json, packages/react-scripts/scripts/utils/frontierInit.js, packages/react-scripts/template/src/index.js, packages/react-scripts/template/styleguide.config.js
Make the app styleguidist behave similarly to zion styleguidist
Update routing to work both locally and when deployed with a nested router.
Later we will figure out a more elegant solution then `FS.appPath`, but that will work for now
=> App styleguidist update and routing fixes

packages/react-scripts/config/webpack.config.js
This will copy any static assets created by webpack. (react-scripts's webpack config)
=> Copy over static assets from @fs and @fs-sandbox shared components.

packages/react-scripts/template/src/components/App.js
`Link` needs to use a relative path in a nested router
=> Update template to fix routing for home link

packages/react-scripts/proxy/setupProxy.js
REMOTE_ENV for int was not falling back correctly to default if the config var did not exist in int
This breaks auth when `REMOTE_ENV=int`
=> Fix env fallback for int

packages/react-scripts/package.json
`proxy` dir isn't included when `npm installed`
=> Add proxy to files in package.json

.travis.yml, README-FRONTIER.md, packages/react-scripts/package-lock.json, packages/react-scripts/package.json, packages/react-scripts/scripts/utils/frontierInit.js, packages/react-scripts/scripts/utils/osUtils.js, packages/react-scripts/template/src/components/App.js
* Update overrides dependencies
New apps were broken because it depends on non-zion-prefixed packages
Also made init fail if the npm installs fail
Remove leading slash on user route to make it a proper relative route
* add test for new app creation
=> Release 1.7.5 - Fix overrides dependencies  (#93)

packages/react-scripts/config/webpack.config.js
This is to allow us to use zion modules npm linked with zero transpilation step (on the zion side)
Also, here are some notes/takeaways from my research on this.
```When using include, we have a whitelist of files to be transpiled.
Trying [paths.appSrc, /node_modules\/@fs/] will result with transpiling any of the 
following filenames
- /User/joey/fs/myApp/src/foo.js -> Transpiled, cause in appSrc
- /User/joey/fs/myApp/node_modules/@fs/Card/index.js -> Transpiled, cause has node_modules/@fs in the filepath
- /User/joey/FOO/node_modules/@fs/Bar/Baz.js -> Transpiled, cause has node_modules/@fs in the filepath, but this is a weird edgecase we weren't really thinking about
BUT when npm linking, webpack see's the Absolute Path, so it sees /User/joey/fs/zion/packages/Card/index.js and that
file …
```
=> allowing webpack to run babel on node_modules/@fs files

packages/react-scripts/package.json
=> ACTUAL 2.0.1 release

packages/react-scripts/scripts/utils/frontierInit.js, packages/react-scripts/template/src/components/example/ExamplePage.js, packages/react-scripts/template/src/components/example/FormCard/EditData.js, packages/react-scripts/template/src/components/example/FormCard/FormCard.js, packages/react-scripts/template/src/components/example/FormCard/ListData.js
* Add `formik` and `yup`
* Add `FormCard` et al.
=> Add form card

packages/react-scripts/proxy/setupProxy.js
When deployed REMOTE_ENV config was overriding TARGET_ENV causing
apps to fail to work correctly outside of beta.
The scopes the env var overrides and other work to only happen when setProxies
is called and when in local dev mode, to remove impact on deployed apps
Tested by running locally with frontier-app-react and the proxies still worked fine. Need to confirm when deployed.
2 primary changes:
- All the logic around setting up the proxies was moved inside the `setProxies` call so it will not execute except when using the proxies. Previously it would execute when required, which happens even when not in dev mode
- As an extra measure of protection, TARGET_ENV is now only overridden if it equals `local`, so we only overwrite that value in local dev mode.
=> Refactor REMOTE_ENV for deployed code

packages/react-scripts/package-lock.json, packages/react-scripts/package.json, packages/react-scripts/proxy/setupProxy.js, packages/react-scripts/template/.storybook/middleware.js
- When frontier-react app runs locally, TARGET_ENV was set to 'beta', instead of 'local'
- This can cause several issues, but was noticed because local apps would only see changes made to 'beta' experiments on XPRMNTL
- Core changed how they wanted to get vars into process after proxy was initially made, making .env/process.env and the way they cascade from fs-config from server the canonical truth, rather than direct vals in fs-config
- Remove REMOTE_ENV usage and anywhere we're getting env vars directly from fs-config
- Remove where we were injecting them into process
- npm linked @fs/react-scripts, made the changes
- used an fs-cra app, ran `fr env` in each env flag to set up .env locally
- tested that process.env.TARGET_ENV was 'local' in each
- tested that default proxy routes still …
=> Remove REMOTE_ENV to fix all the things

packages/react-scripts/package.json, packages/react-scripts/proxy/proxies.js
Required by zion-outage-banner
Outage banner component will be loaded on every app from a global spot, so we'll need a proxy for the url it hits to get data, at /home/banner/currentBanner
=> added /home proxy for upcoming outage banner component

packages/react-scripts/config/webpack.config.js, packages/react-scripts/package-lock.json, packages/react-scripts/package.json
This solves a problem where we were not excluding node_module files from an npm linked repository.
we npm linked storybook-addons into zion, and zion's storybook was transpiling all the node_modules inside of storybook-addons. 
This new logic handles that correctly. If a file's absolute path ever has "node_modules" in it without @fs, then we exclude from transpilation.
=> smarter babel-loader exclusion function

packages/react-scripts/template/src/components/example/ArtifactsViewer.js, packages/react-scripts/template/src/components/example/Banner.js, packages/react-scripts/template/src/components/example/PurposeStatementGenerator.js
fix ArtifactsViewer, Banner, PurposeStatementGenerator
=> Gabe fixes

packages/react-scripts/scripts/utils/frontierInit.js
My PR finally got merged: https://github.com/danvk/source-map-explorer/pull/123
So now we can see gzipped file sizes in our bundle explorer.
=> Default to gzipped source map explorer sizes.

packages/react-scripts/layout/views/layout.ejs, packages/react-scripts/layout/views/partials/sentry.ejs
Sets the following properties on `SERVER_DATA`:
- sentryDSN
- sentryDisabled
- sentryRelease
- targetEnv
`sentryRelease` is formatted like: 
`{appName}@{EFBuildNum}:{ShortGitSHAHash}`, i.e.
`frontier-app-react@172:6386b217`
=> Add Sentry config to app pages

packages/react-scripts/config/webpack.config.js
When using --profile, there is an error that it can't find react-dom. This fixes that error.
Made change locally in node_modules and confirmed `npm run build:prod` worked without the error.
=> Fix issue with --profile

docusaurus/docs/running-tests.md
This instruction is no longer necessary, so I removed it.
=> Remove deprecated doc instruction

packages/react-scripts/proxy/proxies.js
The RIP team is adding an image viewer component. We need urls proxied on the /dz path to load deep zoom images.
=> Add the path /dz in the proxy list

packages/react-scripts/config/webpack.config.js
When using the `--profile` option, there is an error because react-dom is defined twice in the aliases
This moves the profile override to the end so it always wins
Tested locally by modifying the config in node_modules, fixes problem with build when enabling profiling
=> Fix profiling configuration

packages/react-scripts/layout/views/layout.ejs, packages/react-scripts/package.json
The Geo redirect is breaking the loading of the manifest. According to https://stackoverflow.com/questions/51777346/cookies-not-sent-with-request-for-web-app-manifest-json if you set crossorigin even though the request is not crossorigin, it will allow the cookies to be sent with the request, fixing the geo redirect issue.
We tested this with the Africa geo app and it seems to work.
=> add crossorigin to manifest link for geo redirect

packages/react-scripts/layout/views/layout.ejs, packages/react-scripts/package.json
after discussion, it was decided to use `geoData` instead of `geodata` for consistency with other similar variables
=> rename geodata to geoData for consistency

packages/react-scripts/config/webpack.config.js, packages/react-scripts/package-lock.json, packages/react-scripts/package.json, packages/react-scripts/scripts/utils/createJestConfig.js
This loader allows us to use .graphql/.gql files which is especially useful for Zion-CMS which relies heavily on GraphQL fragments. When compiled by webpack, we don't have to worry about cyclical dependencies.
Corresponding Zion-CMS draft PR: https://github.com/fs-webdev/zion-cms/pull/68
=> add graphql-tag loader

CHANGELOG-FRONTIER.md, packages/react-scripts/package.json
Releases the support for gql files.
Due to this issue: https://github.com/facebook/create-react-app/issues/11773 we need to hard pin react-error-overlay to 6.0.9 as 6.0.10 does not work.
=> Release 6.2.0 - Support gql files and pin react error overlay

packages/react-scripts/layout/views/layout.ejs, packages/react-scripts/package.json, packages/react-scripts/scripts/coalesceLocales.js
Some tweaks and changes we can consider for per-locale
The logging could be opt-in or truncated for final release if we choose
It adds a collision report during coalesce so teams are aware of key collisions
=> Perlocale tweaks

packages/react-scripts/package.json, packages/react-scripts/scripts/utils/createJestConfig.js, packages/react-scripts/scripts/utils/jest.RawLoaderStub.js
Mirror what we're doing in zion by just adding an empty module for jest.
=> Fix /coalesce-locales moduleNameMapper in jest tests.
