fs-webdev/create-react-app

- CHANGELOG-FRONTIER.md
- packages/react-scripts/config/webpack.config.dev.js
- packages/react-scripts/config/webpack.config.prod.js
- packages/react-scripts/package.json
This allows dependendies on modulized Polymer 3 components that use wci18n for translations.
> Add support for webpack-wci18n

- .travis.yml
- CHANGELOG-FRONTIER.md
- packages/react-scripts/package.json
- packages/react-scripts/scripts/utils/frontierInit.js
- Pin webpack to make cra happy
- Change the email being used in the deploy stage of travis so artifactory info is more correct
> 1.4.3 release

- packages/react-scripts/scripts/utils/frontierInit.js
- packages/react-scripts/template-ef/hooks/pre-build/npm-build/create-npmrc.sh
- packages/react-scripts/template-hf/src/setupProxy.js
- packages/react-scripts/template-hf/views/index.ejs
> Addressing some issues

- packages/react-scripts/scripts/utils/frontierInit.js
> matching the dep versions to react-scripts

- packages/react-scripts/config/webpack.config.js
> adding react and react-dom to the webpack.config.js alias section

- packages/react-scripts/scripts/utils/frontierInit.js
- packages/react-scripts/template-hf/views/index.ejs
- packages/react-scripts/template/src/components/App.js
This PR will probably break things until the [subnav PR in zion](https://github.com/fs-webdev/zion/pull/73) gets merged.
> incorporating Subnav into the template

- packages/react-scripts/template/src/components/home/HomeHeader.js
- packages/react-scripts/template/src/components/home/Logo.js
Remove background color
Make logo smaller
> tweak home page style

- .travis.yml
- README-FRONTIER.md
- packages/react-scripts/package-lock.json
- packages/react-scripts/package.json
- packages/react-scripts/scripts/utils/frontierInit.js
- packages/react-scripts/scripts/utils/osUtils.js
- packages/react-scripts/template/src/components/App.js
Update styleguidist-overrides, it had some bad dependencies in it
Update some other dependencies
Fix user route
Try to get a Travis test working, but not quite working yet.
> Fix overrides

- packages/react-scripts/config/zion-webpack.config.js
- packages/react-scripts/package-lock.json
- packages/react-scripts/package.json
> adding docgen to the zion.webpack.config.js

- packages/react-scripts/proxy/proxies.js
> Proxy /ident for helper mode

- packages/react-scripts/package.json
> Add layout directory to files that get installed.

- packages/react-scripts/scripts/utils/frontierInit.js
- packages/react-scripts/template/src/index.js
New Root component will have `ErrorBoundary`. New user hook doesn't need the context.
> Utilize new Root component

- packages/react-scripts/template-hf/index.js
- packages/react-scripts/template-hf/server.js
- packages/react-scripts/template-hf/src/setupProxy.js
- packages/react-scripts/template-hf/views/index.ejs
- packages/react-scripts/template/src/components/example/ExamplePage.js
- packages/react-scripts/template/src/components/example/FrontierDocsCard.js
- packages/react-scripts/template/src/components/example/LearnReactCard.js
- packages/react-scripts/template/src/components/example/ZionCard.js
- packages/react-scripts/template/src/index.js
- packages/react-scripts/template/src/setupProxy.js
- packages/react-scripts/template/src/setupTests.js
Added comments and moved inline styles out.
> Comment additions

- packages/react-scripts/package.json
- packages/react-scripts/template/src/components/example/ExamplePage.js
> fixed gird issues

- packages/react-scripts/template/src/components/example/FrontierDocsCard.js
- packages/react-scripts/template/src/components/example/LearnReactCard.js
- packages/react-scripts/template/src/components/example/NotSignedInCard.js
- packages/react-scripts/template/src/components/example/SignedInCard.js
- packages/react-scripts/template/src/components/example/ZionCard.js
> Card fixes

- packages/react-scripts/config/webpack.config.js
- packages/react-scripts/package-lock.json
- packages/react-scripts/package.json
This avoids duplicate dependencies when npm linked
> Add aliases for peer deps

- packages/react-scripts/template/src/components/example/FormCard/EditData.js
- packages/react-scripts/template/src/components/example/FormCard/FormCard.js
- packages/react-scripts/template/src/components/example/FormCard/ListData.js
> Add Comments

- packages/react-scripts/template/src/App.js
- packages/react-scripts/template/src/components/example/FormCard/EditData.js
- packages/react-scripts/template/src/components/example/FormCard/FormCard.js
This makes it so `TextField` only updates to the error state if the field has been touched. The password field was showing error state (red) while typing in the username field.
> Sorry last one. Touched.

- packages/react-scripts/package-lock.json
- packages/react-scripts/template/src/components/example/ArtifactsCard.js
- packages/react-scripts/template/src/components/example/FrontierDocsCard.js
- packages/react-scripts/template/src/components/example/Logo.js
- packages/react-scripts/template/src/components/example/NotSignedInCard.js
- packages/react-scripts/template/src/components/example/UserCard.js
> Adding PropTypes

- packages/react-scripts/template/.travis.yml
. Setting envvars in travis is still done by hand
> adding a base .travis.yml file

- packages/react-scripts/template/src/components/example/FormCard/FormCard.js
> Fix error log for no children in Card.

- packages/react-scripts/template/src/components/ButtonLink.js
- packages/react-scripts/template/src/components/ButtonLink.stories.js
- packages/react-scripts/template/src/components/example/FrontierDocsCard.js
- packages/react-scripts/template/src/components/example/LearnReactCard.js
- packages/react-scripts/template/src/components/example/ZionCard.js
Is there a better name for this component? Anything I should change about this?
> moving duplicated code to a ButtonLink component

- packages/react-scripts/template/.travis.yml
Correct npm token variable in Travis build
> Fix NPM_TOKEN

- packages/react-scripts/package.json
- packages/react-scripts/template/.travis.yml
> 3.0.0-RC.2 with the fixed .travis.yml in the template

- packages/react-scripts/layout/views/layout.ejs
> Add lang attribute to html template

- freshCraTemplateUpdate.sh
> GitHub auth fresh cra template

- packages/react-scripts/config/webpack.config.js
- packages/react-scripts/package-lock.json
- packages/react-scripts/package.json
Required by zion-analytics
Added react-router alias without whitespace changes this time
> react-scripts: added react-router alias

- packages/react-scripts/scripts/utils/frontierInit.js
- packages/react-scripts/template/.travis.yml
- packages/react-scripts/template/gitignore
- packages/react-scripts/template/src/setupTests.js
Update act for React 16.9
Update some dependencies
Preconfigure Travis for CodeClimate in template
> A few updates for React 16.9

- packages/react-scripts/layout/views/layout.ejs
We are going to try this out and see if it can give us valuable data or not.
> Add AppDynamics browser RUM for React stack

- packages/react-scripts/template/src/components/example/ArtifactsCard.js
- packages/react-scripts/template/src/components/example/UserCard.js
Updates portrait URLS from broken URL to new TPS URL
Fix artifact card when no artifacts are found
Update UserCard to use TypeBlock
Tested with frontier-app-react
> Fix errors with artifacts

- packages/react-scripts/template/.codeclimate.yml
> code climate not to report on *.stories.js files or *.test.js files

- packages/react-scripts/package.json
> fix: bump RC version from 16 to 17

- packages/react-scripts/scripts/utils/frontierInit.js
- packages/react-scripts/template/.travis.yml
Been running/deploying CRAs on Node 12 for months
> Update to Node 12, add test:ci script

- packages/react-scripts/template/.codeclimate.yml
Update code climate similar code threshold to get fewer false positives
> Change code climate similar code threshold to 65

- packages/react-scripts/proxy/proxies.js
- packages/react-scripts/template/src/setupProxy.js
No one should be using this proxy any more. Removing
> remove /tf proxy

- packages/react-scripts/config/webpack.config.js
https://gist.github.com/bvaughn/25e6233aeb1b4f0cdb8d8366e54a3977#create-react-app
https://kentcdodds.com/blog/profile-a-react-app-for-performance
https://github.com/facebook/create-react-app/pull/7737/files
> Add profiling

- packages/react-scripts/package-lock.json
- packages/react-scripts/scripts/utils/frontierInit.js
- packages/react-scripts/template/src/App.js
> fix linting warning

- packages/react-scripts/template/src/__mocks__/@fs/zion-frontend-friends.js
> Added mock to fix test

- .travis.yml
- packages/react-scripts/package-lock.json
- packages/react-scripts/package.json
- packages/react-scripts/template-ef/heroku-prebuild.sh
- packages/react-scripts/template/.travis.yml
- packages/react-scripts/template/src/components/example/HomePage.test.js
- packages/react-scripts/template/src/setupTests.js
Fix Tests
Artifactory Honor the name updates
> Test and artifactory updates

- packages/react-scripts/template/src/components/example/LearnReactCard.js
- packages/react-scripts/template/src/components/example/ZionDesignCard.js
Adding fallback for card height when card is not in a grid
> fallback for cell-width

- packages/react-scripts/template/src/components/example/HomePage.js
- packages/react-scripts/template/src/components/example/PurposeStatementGenerator.js
- packages/react-scripts/template/src/components/example/WagonWheel.js
minor tweaks to the template to improve accessibility
> More template fixes

- packages/react-scripts/scripts/utils/frontierInit.js
> Update to zion-ui 7 and zion-root 4

- packages/react-scripts/layout/views/layout.ejs
- packages/react-scripts/layout/views/partials/sentry.ejs
Created a pre-release and deployed and ran into some problems. These are the fixes.
Tested deployed to frontier-app-react
> Fixes to sentry config

- packages/react-scripts/package.json
- packages/react-scripts/template/src/components/example/HomePage.js
> remove extraneous and bug-causing braces

- packages/react-scripts/package.json
- packages/react-scripts/scripts/utils/frontierInit.js
- packages/react-scripts/template/src/components/example/HomePage.js
> Fix bug on HomePage cause by extraneous braces

- packages/react-scripts/package.json
- packages/react-scripts/scripts/utils/frontierInit.js
- packages/react-scripts/template/src/components/example/HomePage.js
- packages/react-scripts/template/src/components/example/HomePageSkeleton.js
- packages/react-scripts/template/src/components/example/I18nPage.js
- packages/react-scripts/template/src/components/example/ResponsiveDebug.js
- packages/react-scripts/template/src/components/example/UserInfoPage.js
- packages/react-scripts/template/src/index.js
> fix: LayoutBand usage, unpin sentry browser, default atSize usage

- packages/react-scripts/package.json
- packages/react-scripts/scripts/utils/frontierInit.js
- packages/react-scripts/template/.codeclimate.yml
- packages/react-scripts/template/src/components/example/HomePage.js
- packages/react-scripts/template/src/components/example/HomePageSkeleton.js
- packages/react-scripts/template/src/components/example/I18nPage.js
- packages/react-scripts/template/src/components/example/ResponsiveDebug.js
- packages/react-scripts/template/src/components/example/UserInfoPage.js
- packages/react-scripts/template/src/index.js
> Release 4.1.5

- packages/react-scripts/template/src/setupProxy.js
> Removing broken docs link

- packages/react-scripts/package.json
- packages/react-scripts/scripts/utils/createJestConfig.js
- packages/react-scripts/scripts/utils/frontierInit.js
I know the app template tests pass because Travis creates a new app, then runs tests, and those tests pass.
I updated to zion-testing-library v5 in my app and then npm-linked to react-scripts to test the jest setup.
Also, I updated the pin a minor version. **This may need to be a major pin update** because the jest-dom version was updated 2 versions and react-scripts is used directly by apps for jest.
> Update zion testing library and other jest packages.

- packages/react-scripts/config/webpack.config.js
- packages/react-scripts/package-lock.json
- packages/react-scripts/package.json
- packages/react-scripts/proxy/setupProxy.js
- packages/react-scripts/scripts/utils/frontierInit.js
- packages/react-scripts/template-hf/server.js
- packages/react-scripts/template-hf/src/setupProxy.js
> necessary tweaks for getting of github deps

- packages/react-scripts/polyfills.js
- packages/react-scripts/template/.storybook/preview.js
> Fixing storybook and adding promise.finally polyfill

- packages/react-scripts/package-lock.json
- packages/react-scripts/package.json
- packages/react-scripts/polyfills.js
- packages/react-scripts/template/.storybook/preview.js
> 4.5.1 - storybook fix and promise.finally polyfill

- packages/react-scripts/template-ef/blueprint.yml
- packages/react-scripts/template-hf/src/setupProxy.js
- packages/react-scripts/template/README.md
> Fixed broken docs urls

- packages/react-scripts/package.json
- packages/react-scripts/scripts/init.js
- packages/react-scripts/scripts/utils/frontierInit.js
> 5.0.0 - this comes with the new template style of initializing a cra

- packages/react-scripts/polyfills.js
Adding array.find to polyfills
> add array.find to polyfills

- packages/react-scripts/package.json
- packages/react-scripts/polyfills.js
> 5.0.1 - array.flat polyfill

- packages/react-scripts/package-lock.json
- packages/react-scripts/package.json
- packages/react-scripts/polyfills.js
core-js doesn't have IntersectionObserver (https://github.com/zloirock/core-js/issues/386)
w3c has the polyfill for this - https://github.com/w3c/IntersectionObserver/tree/master/polyfill
> adding intersection observer polyfill

- packages/react-scripts/package.json
- packages/react-scripts/proxy/proxies.js
> 5.0.2 - adding /dz to proxy list

- .travis.yml
- packages/react-scripts/package-lock.json
- packages/react-scripts/package.json
- packages/react-scripts/template/.travis.yml
> trying to update to jfrog

- packages/react-scripts/proxy/proxies.js
I noticed in changing the other proxy that this one was out of order
> Alphabetizing proxies

- packages/react-scripts/package-lock.json
- packages/react-scripts/package.json
- packages/react-scripts/proxy/proxies.js
> 5.1.0-alpha.0 - trying to test out typescript in our react-apps

- packages/react-scripts/package.json
- packages/react-scripts/scripts/utils/createJestConfig.js
> jest config for mjs and cjs

- packages/react-scripts/layout/views/layout.ejs
- packages/react-scripts/package.json
- packages/react-scripts/proxy/proxies.js
> 5.1.4 version release

- packages/react-scripts/package.json
- packages/react-scripts/polyfills.js
> 5.2.1 with flat-map polyfill

- packages/react-scripts/config/webpack.config.js
- packages/react-scripts/package-lock.json
- packages/react-scripts/package.json
I added a webpack plugin that will retry failed chunks.
> Retry failed chunks with a webpack plugin

- packages/react-scripts/package.json
- packages/react-scripts/polyfills.js
> 5.3.0 - retry chunk load plugin added to webpack

- packages/react-scripts/layout/views/layout.ejs
- packages/react-scripts/package.json
> launchDarklyClientId put into SERVER_DATA in layout.ejs file

- README-FRONTIER.md
- packages/react-scripts/layout/index.js
Fix a couple of frontier docs links
> Update links to frontier docs

- packages/react-scripts/package-lock.json
- packages/react-scripts/package.json
> @fs/auth-middleware needs to be v2 for now.

- packages/react-scripts/layout/views/layout.ejs
Copy envvar value for splitio auth key to SERVER_DATA
> add splitio auth key

- packages/react-scripts/layout/views/layout.ejs
- packages/react-scripts/package.json
> 5.5.0 - splitio auth key var propogated in layout.ejs for zion-config to have access

- packages/react-scripts/package-lock.json
- packages/react-scripts/package.json
> 6.0.0-charlie.0 because beta releases already exist (per-lang testing)

- CHANGELOG-FRONTIER.md
- packages/react-scripts/package-lock.json
- packages/react-scripts/package.json
- packages/react-scripts/scripts/utils/createJestConfig.js
- packages/react-scripts/scripts/utils/frontierInit.js
> resetMocks: false like it used to be, and how we expect it in the cra-template 

- packages/react-scripts/layout/views/layout.ejs
- packages/react-scripts/package.json
Adding geodata returned from snow to SERVER_DATA
> add geodata from snow

- .travis.yml
- packages/react-scripts/package.json
> 6.0.4 release. includes geodata onto SERVER_DATA

- packages/react-scripts/layout/views/layout.ejs
- packages/react-scripts/package.json
> Ejs is annoying 

- package-lock.json
- packages/react-scripts/config/webpack.config.js
- packages/react-scripts/package-lock.json
- packages/react-scripts/package.json
- packages/react-scripts/scripts/utils/createJestConfig.js
> 6.2.0-beta.0 release

- package-lock.json
- packages/react-scripts/package-lock.json
- packages/react-scripts/package.json
- packages/react-scripts/polyfills.js
> fix: swap intersection-observer polyfill

- .travis.yml
adding https config for git to speed up an npm 6 issue
> travis.yml update git config to use https

- CHANGELOG-FRONTIER.md
- packages/react-scripts/package.json
- packages/react-scripts/scripts/coalesceLocales.js
also updated the FRONTIER-CHANGELOG a bit
> debounce the coalesce-locale watch

- CHANGELOG-FRONTIER.md
- packages/react-scripts/package.json
> bumping eslint-config-frontier-react dep for npm 8
